/* Copyright 2026 上海如静知华信息科技有限公司 · https://www.zhuatech.cn/ */
package cn.zhuatech.marketingautomation.deep;import cn.zhuatech.marketingautomation.model.AuditLog;import cn.zhuatech.marketingautomation.repository.AuditLogRepository;import jakarta.persistence.*;import jakarta.validation.constraints.*;import org.springframework.http.HttpStatus;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import org.springframework.web.server.ResponseStatusException;import java.time.*;import java.util.*;
/**
 * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
 */
@Service @Transactional(readOnly=true) public class DeepDomainService{private final EntityManager em;private final AuditLogRepository logs;/**
                                                                                                                                            * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                            */
public DeepDomainService(EntityManager e,AuditLogRepository l){em=e;logs=l;}/**
                                                                                                                                                                                                                        * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                        */
public Dashboard dashboard(String o){return new Dashboard(campaigns(o),consents(o),events(o));}
 /**
  * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
  */
 @Transactional public AudienceView audience(AudienceRequest r){if(r.estimatedSize()<1)throw bad("受众规模必须大于0");var a=new AudienceSegment(r.organizationCode(),r.segmentCode(),r.name(),r.ruleExpression(),r.estimatedSize());em.persist(a);audit("MARKETING_AUDIENCE","创建受众",a.segmentCode,a.ruleExpression);return view(a);}
 /**
  * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
  */
 @Transactional public CampaignView campaign(CampaignRequest r){var a=em.find(AudienceSegment.class,r.audienceId());if(a==null||!a.organizationCode.equals(r.organizationCode()))throw bad("受众不存在或不属于当前组织");if(r.endDate().isBefore(r.startDate()))throw bad("活动结束日期不能早于开始日期");var c=new MarketingCampaign(r.organizationCode(),r.campaignNo(),r.audienceId(),r.name(),r.budget(),r.channel(),r.startDate(),r.endDate());em.persist(c);audit("MARKETING_CAMPAIGN","创建活动",c.campaignNo,c.name);return view(c);}
 /**
  * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
  */
 @Transactional public JourneyView journey(Long id,JourneyRequest r){var c=campaign(id);state(c,"DRAFT");var j=new MarketingJourney(id,r.journeyCode(),r.triggerEvent(),r.actionName(),r.scoreIncrement());em.persist(j);audit("MARKETING_JOURNEY","配置自动旅程",j.journeyCode,j.triggerEvent);return view(j);}
 /**
  * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
  */
 @Transactional public CampaignView approve(Long id){var c=campaign(id);state(c,"DRAFT");var a=em.find(AudienceSegment.class,c.audienceId);long journeys=count("select count(j) from MarketingJourney j where j.campaignId=:id and j.status='ACTIVE'",id);if(a.estimatedSize<1||c.budget<=0||journeys==0)throw conflict("受众、预算和至少一条旅程均完备后才能批准");c.status="APPROVED";audit("MARKETING_CAMPAIGN","批准活动",c.campaignNo,"journeys="+journeys);return view(c);}
 /**
  * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
  */
 @Transactional public CampaignView launch(Long id){var c=campaign(id);state(c,"APPROVED");c.status="RUNNING";audit("MARKETING_CAMPAIGN","启动活动",c.campaignNo,c.channel);return view(c);}
 /**
  * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
  */
 @Transactional public ConsentView consent(ConsentRequest r){var old=em.createQuery("select c from MarketingConsent c where c.organizationCode=:o and c.contactKey=:k and c.channel=:ch",MarketingConsent.class).setParameter("o",r.organizationCode()).setParameter("k",r.contactKey()).setParameter("ch",r.channel()).getResultStream().findFirst().orElse(null);if(old!=null){old.status="GRANTED";old.source=r.source();old.grantedAt=LocalDateTime.now();old.revokedAt=null;return view(old);}var c=new MarketingConsent(r.organizationCode(),r.contactKey(),r.channel(),r.source());em.persist(c);audit("MARKETING_CONSENT","记录营销同意",r.contactKey(),r.channel());return view(c);}
 /**
  * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
  */
 @Transactional public ConsentView revoke(Long id){var c=em.find(MarketingConsent.class,id);if(c==null)throw missing("同意记录不存在");c.status="REVOKED";c.revokedAt=LocalDateTime.now();audit("MARKETING_CONSENT","撤回营销同意",c.contactKey,c.channel);return view(c);}
 /**
  * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
  */
 @Transactional public TouchView touch(Long id,TouchRequest r){var c=campaign(id);state(c,"RUNNING");boolean permitted=em.createQuery("select count(x) from MarketingConsent x where x.organizationCode=:o and x.contactKey=:k and x.channel=:ch and x.status='GRANTED'",Long.class).setParameter("o",c.organizationCode).setParameter("k",r.contactKey()).setParameter("ch",c.channel).getSingleResult()>0;if(!permitted)throw conflict("联系人未授权该渠道营销触达");int score=em.createQuery("select coalesce(max(j.scoreIncrement),0) from MarketingJourney j where j.campaignId=:id and j.triggerEvent=:t and j.status='ACTIVE'",Integer.class).setParameter("id",id).setParameter("t",r.eventType()).getSingleResult();var e=new MarketingTouchEvent(r.eventId(),id,r.contactKey(),r.eventType(),score,r.revenue());em.persist(e);audit("MARKETING_TOUCH","记录营销触点",e.eventId,r.eventType());return view(e);}
 /**
  * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
  */
 private List<CampaignView> campaigns(String o){return em.createQuery("select c from MarketingCampaign c where c.organizationCode=:o order by c.createdAt desc",MarketingCampaign.class).setParameter("o",o).getResultList().stream().map(this::view).toList();}/**
                                                                                                                                                                                                                                                                 * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                 */
private List<ConsentView> consents(String o){return em.createQuery("select c from MarketingConsent c where c.organizationCode=:o order by c.grantedAt desc",MarketingConsent.class).setParameter("o",o).getResultList().stream().map(this::view).toList();}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            */
private List<TouchView> events(String o){return em.createQuery("select e from MarketingTouchEvent e where e.campaignId in(select c.id from MarketingCampaign c where c.organizationCode=:o) order by e.occurredAt desc",MarketingTouchEvent.class).setParameter("o",o).getResultList().stream().map(this::view).toList();}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      */
private MarketingCampaign campaign(Long id){var x=em.find(MarketingCampaign.class,id);if(x==null)throw missing("营销活动不存在");return x;}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          */
private long count(String q,Long id){return em.createQuery(q,Long.class).setParameter("id",id).getSingleResult();}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            */
private void state(MarketingCampaign c,String s){if(!s.equals(c.status))throw conflict("当前营销活动状态不能执行该操作");}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       */
private void audit(String m,String a,String n,String d){logs.save(new AuditLog(m,a,n,"marketing-domain",d));}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    */
private ResponseStatusException bad(String m){return new ResponseStatusException(HttpStatus.BAD_REQUEST,m);}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                */
private ResponseStatusException conflict(String m){return new ResponseStatusException(HttpStatus.CONFLICT,m);}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              */
private ResponseStatusException missing(String m){return new ResponseStatusException(HttpStatus.NOT_FOUND,m);}
 /**
  * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
  */
 private AudienceView view(AudienceSegment a){return new AudienceView(a.id,a.organizationCode,a.segmentCode,a.name,a.ruleExpression,a.estimatedSize,a.status);}/**
                                                                                                                                                                * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                */
private CampaignView view(MarketingCampaign c){return new CampaignView(c.id,c.organizationCode,c.campaignNo,c.audienceId,c.name,c.budget,c.channel,c.status,c.startDate,c.endDate,c.version);}/**
                                                                                                                                                                                                                                                                                                                                                              * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                              */
private JourneyView view(MarketingJourney j){return new JourneyView(j.id,j.campaignId,j.journeyCode,j.triggerEvent,j.actionName,j.scoreIncrement,j.status);}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          */
private ConsentView view(MarketingConsent c){return new ConsentView(c.id,c.organizationCode,c.contactKey,c.channel,c.status,c.source,c.grantedAt,c.revokedAt);}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         */
private TouchView view(MarketingTouchEvent e){return new TouchView(e.id,e.eventId,e.campaignId,e.contactKey,e.eventType,e.scoreDelta,e.revenue,e.occurredAt);}
 /**
  * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
  */
 public record AudienceRequest(@NotBlank String organizationCode,@NotBlank String segmentCode,@NotBlank String name,@NotBlank String ruleExpression,@Positive int estimatedSize){}/**
                                                                                                                                                                                   * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                   */
public record CampaignRequest(@NotBlank String organizationCode,@NotBlank String campaignNo,@NotNull Long audienceId,@NotBlank String name,@Positive double budget,@NotBlank String channel,@NotNull LocalDate startDate,@NotNull LocalDate endDate){}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                         * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                         */
public record JourneyRequest(@NotBlank String journeyCode,@NotBlank String triggerEvent,@NotBlank String actionName,@PositiveOrZero int scoreIncrement){}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  */
public record ConsentRequest(@NotBlank String organizationCode,@NotBlank String contactKey,@NotBlank String channel,@NotBlank String source){}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                */
public record TouchRequest(@NotBlank String eventId,@NotBlank String contactKey,@NotBlank String eventType,@PositiveOrZero double revenue){}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            */
public record AudienceView(Long id,String organizationCode,String segmentCode,String name,String ruleExpression,int estimatedSize,String status){}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              */
public record CampaignView(Long id,String organizationCode,String campaignNo,Long audienceId,String name,double budget,String channel,String status,LocalDate startDate,LocalDate endDate,long version){}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       */
public record JourneyView(Long id,Long campaignId,String journeyCode,String triggerEvent,String actionName,int scoreIncrement,String status){}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     */
public record ConsentView(Long id,String organizationCode,String contactKey,String channel,String status,String source,LocalDateTime grantedAt,LocalDateTime revokedAt){}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              */
public record TouchView(Long id,String eventId,Long campaignId,String contactKey,String eventType,int scoreDelta,double revenue,LocalDateTime occurredAt){}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         */
public record Dashboard(List<CampaignView> campaigns,List<ConsentView> consents,List<TouchView> touchEvents){}
}
