/* Copyright 2026 上海如静知华信息科技有限公司 · https://www.zhuatech.cn/ */
package cn.zhuatech.marketingautomation.deep;import jakarta.persistence.*;import java.time.*;
/**
 * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
 */
@Entity @Table(name="ma_audiences",uniqueConstraints=@UniqueConstraint(columnNames={"organizationCode","segmentCode"})) class AudienceSegment{@Id @GeneratedValue(strategy=GenerationType.IDENTITY)Long id;@Column(nullable=false,length=40)String organizationCode;@Column(nullable=false,length=50)String segmentCode;@Column(nullable=false,length=120)String name;@Column(nullable=false,length=500)String ruleExpression;int estimatedSize;@Column(nullable=false,length=20)String status="ACTIVE";LocalDateTime createdAt;/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 */
protected AudienceSegment(){}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              */
AudienceSegment(String o,String c,String n,String r,int s){organizationCode=o;segmentCode=c;name=n;ruleExpression=r;estimatedSize=s;createdAt=LocalDateTime.now();}}
/**
 * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
 */
@Entity @Table(name="ma_campaigns",uniqueConstraints=@UniqueConstraint(columnNames={"organizationCode","campaignNo"})) class MarketingCampaign{@Id @GeneratedValue(strategy=GenerationType.IDENTITY)Long id;@Version long version;@Column(nullable=false,length=40)String organizationCode;@Column(nullable=false,length=50)String campaignNo;@Column(nullable=false)Long audienceId;@Column(nullable=false,length=140)String name;double budget;@Column(nullable=false,length=30)String channel;@Column(nullable=false,length=20)String status="DRAFT";LocalDate startDate;LocalDate endDate;LocalDateTime createdAt;/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       */
protected MarketingCampaign(){}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      */
MarketingCampaign(String o,String n,Long a,String name,double b,String c,LocalDate s,LocalDate e){organizationCode=o;campaignNo=n;audienceId=a;this.name=name;budget=b;channel=c;startDate=s;endDate=e;createdAt=LocalDateTime.now();}}
/**
 * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
 */
@Entity @Table(name="ma_journeys",uniqueConstraints=@UniqueConstraint(columnNames={"campaignId","journeyCode"})) class MarketingJourney{@Id @GeneratedValue(strategy=GenerationType.IDENTITY)Long id;@Column(nullable=false)Long campaignId;@Column(nullable=false,length=50)String journeyCode;@Column(nullable=false,length=50)String triggerEvent;@Column(nullable=false,length=200)String actionName;int scoreIncrement;@Column(nullable=false,length=20)String status="ACTIVE";/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     */
protected MarketingJourney(){}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   */
MarketingJourney(Long c,String code,String t,String a,int s){campaignId=c;journeyCode=code;triggerEvent=t;actionName=a;scoreIncrement=s;}}
/**
 * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
 */
@Entity @Table(name="ma_consents",uniqueConstraints=@UniqueConstraint(columnNames={"organizationCode","contactKey","channel"})) class MarketingConsent{@Id @GeneratedValue(strategy=GenerationType.IDENTITY)Long id;@Column(nullable=false,length=40)String organizationCode;@Column(nullable=false,length=80)String contactKey;@Column(nullable=false,length=30)String channel;@Column(nullable=false,length=20)String status="GRANTED";@Column(nullable=false,length=80)String source;LocalDateTime grantedAt;LocalDateTime revokedAt;/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         */
protected MarketingConsent(){}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       */
MarketingConsent(String o,String k,String c,String s){organizationCode=o;contactKey=k;channel=c;source=s;grantedAt=LocalDateTime.now();}}
/**
 * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
 */
@Entity @Table(name="ma_touch_events",uniqueConstraints=@UniqueConstraint(columnNames="eventId")) class MarketingTouchEvent{@Id @GeneratedValue(strategy=GenerationType.IDENTITY)Long id;@Column(nullable=false,length=60)String eventId;@Column(nullable=false)Long campaignId;@Column(nullable=false,length=80)String contactKey;@Column(nullable=false,length=50)String eventType;int scoreDelta;double revenue;LocalDateTime occurredAt;/**
                                                                                                                                                                                                                                                                                                                                                                                                                                             * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                             */
protected MarketingTouchEvent(){}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              */
MarketingTouchEvent(String e,Long c,String k,String t,int s,double r){eventId=e;campaignId=c;contactKey=k;eventType=t;scoreDelta=s;revenue=r;occurredAt=LocalDateTime.now();}}
