/* Copyright 2026 上海如静知华信息科技有限公司 · https://www.zhuatech.cn/ */
package cn.zhuatech.marketingautomation;import org.junit.jupiter.api.*;import org.springframework.beans.factory.annotation.Autowired;import org.springframework.boot.test.context.SpringBootTest;import org.springframework.boot.webmvc.test.autoconfigure.AutoConfigureMockMvc;import org.springframework.http.MediaType;import org.springframework.test.web.servlet.*;import java.util.regex.*;import static org.springframework.security.test.web.servlet.request.SecurityMockMvcRequestPostProcessors.httpBasic;import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;
/**
 * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
 */
@SpringBootTest @AutoConfigureMockMvc class DeepMarketingOpsTests{@Autowired MockMvc mvc;
 /**
  * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
  */
 @Test void consentedJourneyCreatesScoredTouch()throws Exception{long a=audience("SEG-1");long c=campaign("CMP-1",a);post("/api/marketing-ops/campaigns/"+c+"/journeys","{\"journeyCode\":\"J-1\",\"triggerEvent\":\"FORM_SUBMIT\",\"actionName\":\"发送白皮书\",\"scoreIncrement\":20}");admin("/api/admin/marketing-ops/campaigns/"+c+"/approve","{}");post("/api/marketing-ops/campaigns/"+c+"/launch","{}");post("/api/marketing-ops/consents","{\"organizationCode\":\"ZH-SH\",\"contactKey\":\"lead-001\",\"channel\":\"EMAIL\",\"source\":\"官网表单\"}");post("/api/marketing-ops/campaigns/"+c+"/touch-events","{\"eventId\":\"EV-1\",\"contactKey\":\"lead-001\",\"eventType\":\"FORM_SUBMIT\",\"revenue\":0}").andExpect(status().isOk()).andExpect(jsonPath("$.data.scoreDelta").value(20));}
 /**
  * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
  */
 @Test void approvalAndConsentGatesAreEnforced()throws Exception{long a=audience("SEG-2");long c=campaign("CMP-2",a);admin("/api/admin/marketing-ops/campaigns/"+c+"/approve","{}").andExpect(status().isConflict());post("/api/marketing-ops/campaigns/"+c+"/journeys","{\"journeyCode\":\"J-2\",\"triggerEvent\":\"CLICK\",\"actionName\":\"通知销售\",\"scoreIncrement\":10}");admin("/api/admin/marketing-ops/campaigns/"+c+"/approve","{}");post("/api/marketing-ops/campaigns/"+c+"/launch","{}");post("/api/marketing-ops/campaigns/"+c+"/touch-events","{\"eventId\":\"EV-2\",\"contactKey\":\"lead-no-consent\",\"eventType\":\"CLICK\",\"revenue\":0}").andExpect(status().isConflict());}
 /**
  * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
  */
 @Test void revokedConsentBlocksFurtherTouch()throws Exception{long a=audience("SEG-3");long c=campaign("CMP-3",a);post("/api/marketing-ops/campaigns/"+c+"/journeys","{\"journeyCode\":\"J-3\",\"triggerEvent\":\"OPEN\",\"actionName\":\"等待两天\",\"scoreIncrement\":2}");admin("/api/admin/marketing-ops/campaigns/"+c+"/approve","{}");post("/api/marketing-ops/campaigns/"+c+"/launch","{}");long x=id(post("/api/marketing-ops/consents","{\"organizationCode\":\"ZH-SH\",\"contactKey\":\"lead-003\",\"channel\":\"EMAIL\",\"source\":\"订阅中心\"}").andReturn());post("/api/marketing-ops/consents/"+x+"/revoke","{}");post("/api/marketing-ops/campaigns/"+c+"/touch-events","{\"eventId\":\"EV-3\",\"contactKey\":\"lead-003\",\"eventType\":\"OPEN\",\"revenue\":0}").andExpect(status().isConflict());}
 /**
  * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
  */
 long audience(String n)throws Exception{return id(post("/api/marketing-ops/audiences","{\"organizationCode\":\"ZH-SH\",\"segmentCode\":\""+n+"\",\"name\":\"高意向制造业客户\",\"ruleExpression\":\"industry=manufacturing AND score>=60\",\"estimatedSize\":1200}").andReturn());}/**
                                                                                                                                                                                                                                                                             * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                             */
long campaign(String n,long a)throws Exception{return id(post("/api/marketing-ops/campaigns","{\"organizationCode\":\"ZH-SH\",\"campaignNo\":\""+n+"\",\"audienceId\":"+a+",\"name\":\"数字化转型增长活动\",\"budget\":50000,\"channel\":\"EMAIL\",\"startDate\":\"2026-09-01\",\"endDate\":\"2026-10-31\"}").andReturn());}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                */
ResultActions post(String u,String b)throws Exception{return mvc.perform(org.springframework.test.web.servlet.request.MockMvcRequestBuilders.post(u).with(httpBasic("operator","operator123")).contentType(MediaType.APPLICATION_JSON).content(b));}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    */
ResultActions admin(String u,String b)throws Exception{return mvc.perform(org.springframework.test.web.servlet.request.MockMvcRequestBuilders.post(u).with(httpBasic("admin","admin123")).contentType(MediaType.APPLICATION_JSON).content(b));}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   */
long id(MvcResult r)throws Exception{var m=Pattern.compile("\"id\":(\\d+)").matcher(r.getResponse().getContentAsString());Assertions.assertTrue(m.find());return Long.parseLong(m.group(1));}}
